# Copyright (c) 2018, NVIDIA CORPORATION.

# Usage:
#   conda build -c defaults -c conda-forge .
package:
  name: libgdf_arrow
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') }}

source:
  # git_url: ../..
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - CC
    - CXX

requirements:
  # use channel:
  #   - defaults
  #   - conda-forge
  build:
    - cmake

  run:
    - pyarrow 0.10.*

test:
  commands:
    - test -f $PREFIX/include/gdf-arrow/gdf-arrow.h    # [unix or osx]
    - test -f $PREFIX/lib/libgdf-arrow.dylib     # [osx]

about:
  home: http://gpuopenanalytics.com/
  license: Apache
  # license_file: LICENSE
  summary: GPU Dataframe core library
